- hosts: all
  become: yes
  become_user: root
  vars:
    pip_executable: pip3
    pip_install_packages:
      - docker
      - docker-compose

  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
  - name: Distribution release
    debug: msg="{{ ansible_distribution_release }}"


  - name: Add universe repository for ubuntu release
    apt_repository:
      repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe
      state: present
  - name: install gnupg2
    apt:
      name: gnupg2
      state: present
      update_cache: true
    when: ansible_distribution_release == 'focal'

  - include_role:
      name: geerlingguy.docker
  - include_role:
      name: geerlingguy.pip

  - name: 'add users to docker group'
    user:
      name: 'vagrant'
      groups: 'docker'
      append: 'yes'
